import Head from "next/head";
import styled from "styled-components";

const Container = styled.div`
  text-align: center;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Tere</h1>
    </Container>
  );
}
